framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
kms_froala_editor:
   # Disable JQuery inclusion.
     includeJQuery: false

     # Disable CodeMirror inclusion.
     includeCodeMirror: false

      # Disable Font Awesome inclusion.
     includeFontAwesome: true

     # Disable all bundle javascripts inclusion (not concerning JQuery nor CodeMirror).
     # Usage: if you are using Grunt or other and you want to include yourself all scripts.
     includeJS: true

     # Disable all bundle CSS inclusion (not concerning Font Awesome nor CodeMirror).
     # Usage: if you are using Grunt or other and you want to include yourself all stylesheets.
     includeCSS: true
     # The image upload folder in your /web directory.
     # Default: "/upload".
     imageUploadFolder: "/public/images"

     # The image upload URL base.
     # Usage: if you are using URL rewritting for your assets.
     # Default: same value as provided as folder.
     imageUploadPath: "/public/images"

     pluginsEnabled: ["image", "file"]