liip_imagine :
    resolvers :
        default :
            web_path : ~

    filter_sets :
        cache : ~
        card_image :
            quality : 100
            filters :
                thumbnail  : { size : [295, 180], mode : outbound }
        gerard :
            quality: 100
            filters:
                thumbnail: { size : [150, 150], mode : outbound }
        image_obs_admin :
            quality: 100
            filters:
                thumbnail: { size : [150, 150], mode : outbound }
        profile_personal_obs_image:
            quality: 100
            filters:
                thumbnail: { size: [80, 80], mode : outbound }